<p>
<h2>
Wednesday 13th of April – Micro
</h2>
9h30	- Breakfast <br>
10h 	- <strong>François Vannucci</strong> (APC), “From the electron to the Higgs boson” – Amphitheatre <br>
<br>
<h3>
10h30 	- 12h30 Poster session - Hallway
</h3>
<strong>Gang Lin</strong>, “A new pore pressure measurement device for rock in the laboratory. Keywords : Permeability, Pore pressure, Pressure difference, Linear relationship ” <br>
<strong>Edwan Preau</strong>, “Holography and Extreme Phases of Matter” <br>
<strong>Juliette Dupeyron</strong>, “Evolution of Fe isotope composition in sedimentary pyrite from Archean to 
Paleoproterozoic: new perspective from microanalyses. Keywords : Pyrite, Archean, Fe isotope composition, SIMS” <br>
<strong>Etienne Le Glas</strong>, “Chlorine isotopes in La Soufrière de Guadeloupe (FWI) fumaroles trace HCl 
scrubbing at shallow depth. Keywords : Isotope geoschemistry, volcanic gases, volcanology” <br>
<strong>Lucile Mellet</strong>, “Hyper-Kamiokande time synchronization system. Keywords : Neutrinos, cerenkov detector, atomic clocks, GNSS” <br>
<strong>Salomé Pannefieu</strong>, “Sodium and magnesium in aluminosilicate melts and glasses: do they get 
along? Keywords : Aluminosilicates, Melts, Glass, Viscosity, Raman spectroscopy, Structure” <br>
<strong>Adrien Donatini</strong>, “Fast and Cerium: A study of redox kinetics in aluminosilicate melts. Keywords : In situ measurement, Redox kinetics” <br>
<strong>Robin Bonnet</strong>, “Biochemical Degradation Mechanisms of Cementitious Matrices: Application to 
Asbestos Cement Wastes. Keywords : Concrete, Waste Treatement, Chrysotile, Organic Acids, Lactobacillus” <br>
<strong>Martin Colledge</strong>, “Influence of Small Sinusoidal Stress Perturbations on Microseismic Triggering at 
the Laboratory Scale. Keywords : Seismology, Experimental, Rock Mechanics” <br>
<strong>Amicie Delahaie</strong>, “Rock-Eval®-RMQS: Studying the Characteristics of Soil Organic Matter in 
France with Rock-Eval® 6 Thermal Analysis to Evaluate its Stability. Keywords : Biogeochemistry, Organic carbon, Biogeochemical stability, Thermal Analysis” <br>
<strong>Augustin Thomas</strong>, “Tidal oscillations in boreholes reveal hydrodynamic as well as elastic properties 
of aquifers. Keywords : Hydrogeology, Poroelasticity, Tides” <br>
<strong>Haoxuan Sun</strong>, “Metal-silicate silicon isotopic fractionation. Keywords : Cosmochemistry” <br>
<strong>Valentina Raskina</strong>, “Research and Development of the High Granularity Timing Detector for ATLAS experiment. Keywords : Physics, LHC, CERN, Detector, LGAD” <br>
<Strong> Sébastien Faes</strong>, "A first look on long period coherence in InSigth data" <br>
<br>
<h3>
14h – 17h Presentations – Amphitheatre
</h3>
<strong>Théo Briolet</strong>, “Experimental study of microstructural controls on the weathering of carbonate rocks” <br>
Abstract : Interactions between water and carbonate rocks are involved in various issues such as CO2 storage, karst development and coastal weathering. A better understanding of the influence of pore structure on the weathering of carbonate rocks remains a key issue. An integrated multiscale experimental workflow was thus developed to study microstructural controls on the dissolution processes. Two different carbonate formations have been considered in this study. Although their mineralogy is similar, their microstructure is significantly different. Coreflooding experiments where CO2-saturated water was injected at a flowrate of 140 cm3/h for 5 days were carried out on 80-mm and 100-mm long samples. Chemical concentrations of dissolved species in the effluents were determined and thermodynamic modelling was used to estimate the outlet fluid saturation indexes. Samples petrophysical and petroacoustic properties were measured before and after coreflooding experiments. These measurements were completed by scanner and microscanner imaging, SEM observation and BET analysis. The dissolution patterns of Lavoux limestone are dominated by the development of localized dissolution channels ("wormholes"). Although the dissolution of Euville limestone appears more diffuse, microtomography has highlighted a preferential dissolution localized in specific more microporous areas. Microstructural characterizations based on BET analysis and SEM observations, combined with mini-coreflooding experiments performed on limestone powder, show that the higher dissolution kinetics of Lavoux limestone is mainly related to a larger specific surface area leading to a higher reactivity. Moreover, BET measurements revealed similar specific surface areas for the bulk rock and powder samples suggesting that most of the specific surface area is held at the microporous grain scale.<br>
<strong>Kun Zheng</strong>, “Selective leaching of indium from end-of-life LCD panels by desferrioxamine E”<br>
Abstract : The increasing consumption of electrical and electronic equipment has made recycling from end-of-life (EoL) products a key strategy for the stable supply of technology-critical elements and the development of a circular economy as proposed by the European Union (EU). The sustainable supply of indium, which is listed as a critical raw material by EU commission, is a major concern due to its high economic value. As one of major electronic waste (e-waste), liquid crystal display (LCD) panels are a potential resource for indium recovery because the indium-tin oxide layer in the LCD panels contains 80-90 wt% In2O3. Aimed to recycle indium from EoL LCD panels, biohydrometallurgy is environmentally benign as it does not involve highly acidic or alkali as well as toxic chemicals, consumes less energy and is more suitable to extract valuable metals as compared to conventional chemical hydrometallurgy and pyrometallurgy. Here, we develop an innovative and alternative technology to selectively leach indium from EoL LCD panels using Desferrioxamine E (DFOE), a natural chelator-siderophore, which has a less environmental impact compared with chemical synthesized compounds. Furthermore, DFOE exhibits a strong ability to bind indium, meanwhile, the metal complex resulting from the bioleaching has a high stability constant. The indium in the LCD panels first concentrated by a pre-treatment, including dismantling, removing polarizers, crushing, milling and sieving to obtain different size fractions. Characterization of LCD panels was analyzed by scanning electron microscope, X-ray fluorescence, and ICP-MS. The optimal conditions and the best capacity of leaching were determined by analyzing the influence of various parameters, including pH, pulp density, particle size, and the concentration of DFOE. The results showed that at neutral pH and 5 g/L of pulp density, for the smaller particle (<36 μm) with a high DFOE/EoL ratio (i.e. r = 20) corresponded to the highest leaching capacity. <br>
<strong>Jani Kastikainen</strong>, “Investigations of quantum critical systems”<br>
Abstract : In this talk, I will describe some aspects of my research on two-dimensional conformal field theories with boundaries. Conformal field theories are examples of quantum field theories that provide effective continuum descriptions of quantum many-body systems near a critical point. When the system has a boundary (a wall or a mirror), its entanglement and correlation properties are affected. After giving a brief introduction to the subject, I will show how entanglement entropies of subsystems and correlation functions of field operators are affected by the boundary. Some parts of my work utilise the relationship between quantum field theory and gravity known as the holographic duality which I might explain depending on time constraints. <br>
15h – Break <br>
<strong>Lukas Maderer</strong>, “Measuring the Earth’s density profile with atmospheric neutrinos” <br>
Abstract : The Earth’s interior has been investigated for centuries to find out its inner structure. By analyzing the propagation of seismic waves one found that our planet consist of an Iron core surrounded by a pyrolytic mantle. Density models like PREM provide an approximate one-dimensional profile of Earth. Yet many theories like core-mantle convections highly depend on exact knowledge of certain densities. In this contribution a novel technique that could improve the understanding of the inner structure of the Earth with atmospheric neutrinos is presented.
In particle showers triggered by comsic rays interacting with atoms in the atmosphere, high energetic neutrinos are produced continuously. During their propagation through Earth, they undergo so called neutrino oscillations, meaning they change their flavor eigenstate. The probability for this phenomenon to occur depends among others on the electron density along the neutrino path. Neutrino detectors are able to measure the flavor ratio of the detected particles and consequently draw conclusions about the Earths density.
Here it is shown what limits can be set on the density of certain Earth layers, for both existing detectors and possible future experiments. I also report the possibility to investigate properties of LLSVPs, disturbances in the shear wave velocity that are believed to origin from density anomalies in the lower mantle. <br>
<strong>Xiaoquan Qin</strong>, “Geochemistry of trace metals associated with Fe-Mn nodules (FMN) of red soil 
profiles in China” <br>
Abstract : Red soil is widespread in southern China, covering an area of about 22.7% of China’s area. It has experienced intense syndepositional pedogenesis under humid tropical to subtropical conditions. In such soil profile, Fe and Mn oxides are omnipresent and frequently occur in Fe-Mn nodules of varying morphology, size, and shape. Due to their high surface area and high surface charge density, Fe and Mn oxides play crucial roles in concentrating and immobilizing trace metals in red soils. On the other side, Fe-Mn nodules are very sensitive to soil environmental changes, such as moisture, pH, redox potential, and microbial activity. Trace metals may be released due to organic fertilization of the soil or long-term saturation with water, leading to contamination of the soil as well as the soil solution and groundwater. Therefore, study on the geochemical behavior of trace metals associated with Fe-Mn nodule in red soil profile could help with improving our knowledge of trace metal cycling and their potential risk in such soil system, and also elucidating soil environmental changing which was recorded by nodules. <br>
<strong>Tri Dung Nguyen</strong>, “Photometric modeling for the characterization of planetary surfaces” <br>
Abstract : Photometry, which exploits the signal obtained from multi-angular and multi-spectral remote sensing data, is very important in planetary science because it is often the only source of information about the Solar System bodies. The behavior of light on the surface is recorded as the Bidirectional Reflectance Distribution Function (BRDF). The combination of radiometric data acquired at several scales, phase angles and wavelengths will allow to access the physical properties of the surface. We will focus on the determination of the BRDF of the surface of the Earth (Asal-Ghoubbet rift, Republic of Djibouti) and of the Moon. To conduct this research, data from various instruments are actively gathered: laboratory and field goniometers, drones and satellites (Pleiades, Lunar Reconnaissance Orbiter…). We will then use these data with radiative transfer models to extract soil physical properties: surface roughness, porosity, grain size and shape, particle size distribution, micro-texture, mineralogy, water content, etc. They are the keys to improve our understanding of the formation and evolution of soils and landscapes, and contribute to the preparation of future space missions (rover mobility, landing). During my talk, I will detail about the scope of my research. I will also present the state of progress of my work and what remains to be done in the near future. <br>
<strong>Runa van Tent</strong>,“Global mantle density tomography using Earth’s free oscillations” <br>
Abstract : Constraints on the 3-D density structure of Earth’s mantle provide important insights into the nature of global-scale mantle convection. Two regions of particular interest are the Large Low Shear Velocity Provinces (LLSVPs) in the lower mantle under Africa and the Pacific, which may be rising (super-)plumes or dense, stable piles. The only seismic data directly sensitive to density variations throughout the entire mantle are normal modes: whole Earth oscillations that are observed after large earthquakes. However, their sensitivity to density is weak compared to the sensitivity to seismic velocity and previous studies have presented conflicting density models of the lower mantle, showing either entirely light or entirely dense LLSVPs. Here, we present our new models of 3-D mantle velocity, density and discontinuity topography, obtained from the inversion of recent normal-mode measurements using a Hamiltonian Monte Carlo algorithm, which also provides us with model uncertainties. We find a large high-density region in the bottom-300 km of both LLSVPs, while the remaining LLSVP material has a lower-than-average density. These partially dense LLSVPs imply that they are at least partially compositionally distinct, as temperature variations alone cannot decorrelate seismic velocity and density. Furthermore, we compare our density model to the density structure obtained from a range of models of thermochemical convection and assess whether our density model can distinguish between different thermochemical scenarios. <br>
<br>
<h3>
14h – 17h Presentations – room Outremer
</h3>
<strong>Emilie Pirot</strong>, “Exploring Greenland seismicity with Machine Learning” <br>
Abstract : Greenland and polar regions in general are highly sensitive to global warming. Impacts on Greenland’s glaciers may be observed through the increasing number of calving events. 
To better understand this impact, it’s important to be able to quantify and document the calving activity. However, direct observations are impossible to perform recurrently over long-time period because of the weather and of the lack of human witnesses. 
The deployment of a seismological network in Greenland has able the recording at regional scales of seismic signals generated by calving events, which are called glacial earthquakes.
The seismic signal generated by calving events presents a broadband frequency range and a wide
diversity of waveform which make them difficult to discriminate from tectonic events as well as anthropogenic and natural noises.
Starting from two catalogs of known events, one for glacial earthquake events which occurred between 1993 and 2013 and one for earthquakes which occurred in the same time period, we trained and tested a detection algorithm based on the STA/LTA method to extract signals’ events from continuous data. 
Then, a machine learning processing chain allows the signal’s quick automatic classification onto different classes : glacial earthquakes, earthquake and noise, with the probability of belonging to this class. Signals are gathered to form events, which increase the algorithm’s accuracy. We here present a catalog of new seismic events, identified with our method.
The algorithm performances are tied with the choice of parameters. We will thus discuss the importance of features chosen to describe glacial earthquake seismic signals and analyze how the contribution of machine learning can step up the understanding of glacial earthquakes events.
We investigated a 400 days spanning time of continuous data from the Greenland regional seismic network and identified new glacial earthquakes events with the Random Forest machine learning algorithm to create a catalog. This processing chain will be deployed on other time period to expand our catalog. <br>
<strong>Alice Dupiau</strong>, “Modeling spectral and directional soil reflectance in the solar domain (400-2500 nm) 
as a function of moisture content” <br>
Abstract : Soil moisture content (SMC) plays a key role in the interactions between land surfaces and the atmosphere. Its estimation is essential for applications such as agriculture, hydrology, climate, or defense. Since the 1970s, remote sensing has emerged as a promising tool for mapping SMC over large areas. Different wavelength ranges can be used: solar (0.3-3 µm), thermal infrared (3-12 µm), and microwave (0.5-100 cm). The longer the wavelength, the deeper the water can be probed. In the solar domain, light penetrates very little into the soil because it is quickly absorbed: SMC is estimated over a maximum depth of about one millimeter.
MARMIT-2 (Dupiau et al. 2022. Remote Sens. Environ.) is a two-layer radiative transfer model that depicts a wet soil as a dry soil topped with a thin layer of a mixture of water and soil particles. The reflectance spectrum of wet soil is expressed as a function of the reflectance spectrum of the corresponding dry soil and four input parameters: a fixed one, the complex refractive index of soil particles, and three free ones, the thickness of the water layer, the surface fraction of wet soil, and the volume fraction of soil particles in the water layer. MARMIT-2 has been validated on a database of 225 soil samples whose reflectance spectra have been measured in the laboratory at various moisture contents. The work in progress consists in the extension of MARMIT-2 to larger spatial scale for its operational use in remote sensing. <br>
<strong>Baptiste Thomas</strong>, “Caracterising convective mixing efficiency in a terrestrial magma ocean” <br>
Abstract : Geochemical heterogeneities formed at the very beginning of the Earth's history are found in modern oceanic basalt samples. Such observations raise many questions, including the efficiency of mixing in the Earth's mantle. 
However, during the first hundred million years, likely as a result of the Moon-forming giant impact, the Earth experienced a magma ocean episode over the entirety, or a large part, of the thickness of the mantle.
A quantitative understanding of mixing in the magma ocean is then key to interpreting geochemical observations of very short-lived isotopes.
In our work, we use 3D numerical simulations in a spherical shell to study convection and quantify the efficiency of mixing processes in a magma ocean.
Due to the low viscosity of the magma ocean we take into account inertial effects, and also examine the effects of rotation. Our simulations couple convection with a study of Lyapunov exponents to quantify mixing. <br>
15h – Break <br>
<strong>Angèle Laurent</strong>, “Source Characterisation of the Very Long Period Earthquakes of the Mayotte 
ongoing Seismo-Volcanic Crisis” <br>
Abstract : VLF (Very Low Frequency) events of the ongoing seismovolcanic crisis of Mayotte detected through a single-station time-frequency detector with data that comes from local and regional stations in Mayotte, Comoros and Madagascar. We incorporate OBH (Ocean Bottom Hydrophones) data installed during marine campaigns aboard the R/V Marion Dufresne II, between May and July 2019 [Feuillet et al., 2019], and shorter campaigns since July 2019. The correction of the OBH pressure data into acceleration [An et al., 2017] allow us to perform analysis like location and modelling and observe the complexity of the source mechanism in the VLFs signal at local scale. Event location is performed though spatial 3D back-projection of station-pair cross-correlation functions [Poiata et al., 2016], assuming a velocity of 3.5 km/s.
While the VLF epicentral location is reasonably well constrained 20 km east of Petite-Terre by the back-projection analysis, depth resolution is poor. For this reason, we explore VLF depth and focal mechanism from direct modelling of the signal at local scale using discrete wavenumber summation [Cotton and Coutant, 1997]. Synthetic seismograms generated using a simple 1D model and an isotropic focal mechanism provide a good ct with the observed signals. We found that VLFs are located above 25 km of depth, on the top of the seismic swarm, east of Petite-Terre. We further explore the spatio-temporal link between the VLFs and the volcano-tectonic seismicity and the possible source models for VLFs. <br>
<strong>Raphaël Bajou</strong>, “Assessing rock strength distribution in lava dome with muon tomography” <br>
Abstract : The intense hydrothermal activity occurring at La Soufrière de Guadeloupe, French Lesser Antilles, is a major concern for both volcanologists at the Volcanological and Seismological Observatory of Guadeloupe and for the local population living nearby. Partly hosted within the andesitic lava dome, this hydrothermal system, continuously fueled with meteoric waters, is indeed responsible for both violent phreatic eruptions (the last major event occurred in 1976-1977), and fast rock alteration due to hot and acid fluid circulation that worsens the risk of a partial volcano flank collapse. 
Since 2015, the deployment of scintillator-based particle trackers built in IP2I, Lyon, to perform dynamic muon tomography of the lava dome structure has allowed to increase the knowledge of the hydrothermal activity. 
The method is similar to X-ray radiography, where the particles are absorbed according to the mass density distribution along the traveled path. Muon tomography involves performing a radiography of a geological body of large dimensions by using a single detector.
Here we will present new results obtained with data acquired with the last generation of those detectors installed in south and east of the volcano to scan different areas of the lava dome. The results obtained with real data  were put in comparison with simulation studies, allowing a better characterization of the muon signal/background, which will further improve the quality of the dome 3D density reconstruction. <br>
<strong>Marie Vulliet</strong>, “Erosional dynamics of a river driven by groundwater seepage” <br>
Abstract : Seepage erosion occurs when groundwater emerges at the surface of a granular heap. A spring forms and feeds a river which entrains sediments, thus changing the groundwater flow. We reproduce this phenomenon in the laboratory using a quasi-2D aquifer filled with glass beads, by imposing a water level at one end of the pile. Water flows through the aquifer and emerges at the surface of the granular bed. For large enough water levels this river erodes its bed and the spring progressively ascends the heap. We investigate its trajectory, the evolution of the groundwater discharge and the river depth. Intriguingly, we find that after an initial erosive period the river attains a new equilibrium profile, with an elevated spring. We model the flow in the aquifer using Darcy's law, predicting the shape of the water table, the position of the spring and the groundwater discharge. By applying Coulomb’s frictional law to the forces experienced by a grain we predict a threshold for the onset of erosion as a function of reservoir height and aquifer length. This prediction provides a dynamical theory for the erosional dynamics of the river. Our combined theoretical and experimental approach thereby helps constrain the response of an idealized erosive river-catchment system to steady forcing. <br>
<br>
<h2>
Thursday 14th of April – Macro
</h2>
9h30 – Breakfast <br>
10h – <strong>Sara Maleubre (LPNHE)</strong> “Successes and challenges of the Standard Cosmological model” - Amphitheatre <br>
<br>
<h3>
10h30 – 12h30 Poster session - Hallway <br>
</h3>
<strong>Anaïs Rusquet</strong>, “Volcanism in the Comoros Archipelago : New K-Ar ages and geochemical data”, Keywords : Volcanism, K-Ar ages, geochemistry <br>
<strong>Léna Arthur</strong>, “Numerical study of accretion flows in a supermassive black hole binary system during 
merger” <br>
<strong>Guy Augarde</strong>, “NaCL : Nouvel algorithme pour Courbes de Lumière”. Keywords : Cosmology, SN Ia <br>
<strong>Léon Vidal</strong>, “LISA ON TABLE: Simulating interferometric signals and testing TDI”. Keywords : Gravitational Waves, Instrumentation, Interferometry, LISA, TDI <br>
<strong>Mohammad Amin Aminian</strong>, “Ocean floor seismological and environmental monitoring”. Keywords : Seismology, ocean bottom seismometer stations, RHUM-RUM experiment, MicroSeismic <br>
<strong>Raphaël Kou</strong>, “Dark matter, galaxies and gas cross-correlations: towards a better understanding of 
our universe large-scale structure”. Keywords : Cosmology, CMB, galaxies, gravitational lensing, Sunyaev-Zel'dovich, cross-correlations <br>
<strong>Bryan Raimbault</strong>, “Coseismic and Early Postseismic deformation of the Mw7.2 Nippes (Haiti) 
Earthquake”. Keywords : Seismotectonics, Geodesy, Earthquake, InSAR, Seismic Hazard <br>
<strong>Arthur Walbecq</strong>, “Characterizing the efficiency of magma oceans degassing”. Keywords : Planet formation, Fluid dynamics, convection <br>
<strong>Louis-Marie Gauer</strong>, “Data-driven gap filling and spatio-temporal filtering of the GRACE-GRACE-
FO records”. Keywords : GRACE, M-SSA, Satellite Gravimetry, Spatio-temporal field variations, Signal Processing <br>
<strong>Laëtitia Pantobe</strong>, “Monitoring shallow volcanic seismicity at La Soufrière de Guadeloupe : new 
constraints from relative location and detection of a cyclic swarm activity”. Keywords : Volcanic seismicity - Hydrothermal system - Seismic swarm - Relative location – Cyclicity <br>
<strong>Christos Ntinos</strong>, “Global infrared mosaics of Enceladus based on new navigation calculations”. Keywords : Icy moons, VIMS, Cassini-Huygens, Infrared maps <br>
<strong>Marouchka Froment</strong>, “The seismic source of meteorite impacts”. Keywords : Seismology, Shock Physics <br>
<strong>Arthur Delorme</strong>, “Learning methods for the calculation of deformation maps from optical images”. Keywords : machine learning, tectonics, image processing, ground deformation <br>
<strong>Mario Fernandez</strong>, “A benchmark study of deep learning methods for seismic interpolation”. Keywords : seismic, interpolation, deep learning <br>
<strong>Wanbo Xiao</strong>, “First attempt to dynamically model the InSight Lander vibrations”. Keywords : Martian Seismology <br>
<strong>Jing Shi</strong>, “Re-investigate the Moon deep interior”. Keywords : Deep moonquakes, Moon interiors, Seismology <br>
<br>
<h3>
	14h – 17h Presentations – Amphitheatre
</h3>
<strong>Alexandra Perron</strong>, “Thermal analyses of biocarbonates as part of the search for traces of life in 
planetary environments” <br>
Abstract : The search for organics in extraterrestrial environments is the primary strategy to highlight a potential extinct or extant life. One alternative method is to search for the presence of biologically-formed minerals, probably more resistant in such environments and capable of preserving remnants of biological organic matter. The goal is then to distinguish bio- and organo-minerals from their abiotic counterparts by using instruments as close as possible to in situ space ones such as pyrolysis coupled with gas chromatography (GC) and mass spectrometry (MS).
Carbonates are abundant minerals on Earth that are formed mostly by biological activity. Pyrolysis performed by differential thermal analysis (DTA) show differences of at least 20°C in phase transition temperatures between abiotic Mg- and Ca-carbonates and their natural (modern and fossil) or laboratory biogenic counterparts. DTA-MS analysis as well as Rock-Eval analysis also reveal that the intracrystalline biological organic matter trapped in bio-related minerals can be thermally dissociated from organic compounds adsorbed on the mineral surface. Additional single and dual injection pyrolysis-GC-MS can identify these organic compounds released at different temperatures. Overall, each pyrolysis technique provides complementary information on the organic matter trapped in bio-related carbonates’ crystalline structure. Thermal analysis would then have the potential to distinguish bio-related carbonates from abiotic carbonates and to highlight their ability to preserve associated organic molecules of biological origin. Those approaches could be used for the search for possible records of life in extraterrestrial environments such as Mars, Enceladus, Europa and Titan by current and future space exploration missions. <br>
<strong>Julien Marchioro</strong>, “Searching progenitors of gravitational waves, the evolution of massive binary 
stars”<br>
Abstract : Since the first detection of Gravitational waves in 2015, a new era in observatory astronomy has begun. Two black holes that come sufficiently close can merge and generate GW, but what leads to this binary black holes formation ? We investigate the evolution of massive binaries, to constraint the possible scenarios of evolution that can lead to the formation of binary black holes. <br>
<strong>Baptiste Jost</strong>, “Novel method for joint systematic correction and foreground cleaning and its 
application to the estimation of cosmic birefringence in Simons Observatory.” <br>
Abstract : The primordial B modes signal in the CMB is very faint and polluted by other polarised astrophysical signals. The future and present experiments that aim at constraining the tensor to scalar ratio are limited by the efficiency with which they are able to remove this contaminating signal. Furthermore exquisite knowledge of the instrument is necessary to understand possible systematic effects that could bias the data. The interplay between systematic effects and foreground cleaning can be critical in the estimation of cosmological parameters. 
I developed a generalisation of a parametric component separation method that allows for the estimation of systematic parameters alongside foreground spectral indices while taking into account their possible interplay. I can then retrieve a CMB map that is foreground cleaned and corrected for systematic effects. Furthermore the statistical error on the estimation of systematic parameters and spectral indices can be analytically evaluated and propagated to the cosmological parameter estimation, making this method statistically robust. 
In particular I focus on the joint estimation of the tensor to scalar ratio and isotropic cosmic birefringence. The latter is completely degenerate with the polarisation angle of the telescope. I demonstrate that using a calibration prior and the generalised component separation I am able to constrain the tensor to scalar ratio and the birefringence angle using the example of the Simons Observatory Small Aperture Telescopes.  <br>
15h – Break <br>
<strong>Guest session – PhD candidates from GRNE doctoral school</strong> <br>
<strong> Charles Masquelet </strong> <br>
<strong>Igor Rzeplinski</strong>, “Xenon chemistry at high pressure, geochemistry concerns” <br>
Abstract : Xenon (Xe) is the heaviest element among the five stable noble gases (NGs). As such, it has always been considered as chemically inert. However, a longstanding knowledge about its ability to react with strong oxidizing agents at room pressure and temperature raises the question of its chemical reactivity in geologic reservoirs. Moreover, the Xe paradox, which consists in elemental and isotopic inconsistencies, requires a mechanism specific to Xe. Here we present mass spectrometry analysis on feldspars and olivine heated at around 1,000 K and 3.5 GPa. This thermal treatment fractionates Xe up to +2.30 ± 0.19 permil per atomic mass unit (‰.amu⁻¹). This chemical mechanism, conjugated to planetary early stage collisions, is suitable to explain both aspects of the Xe paradox. <br>
<strong>Antoine Collet</strong>, “Automated history matching in reactive transport. Application to the uranium in-
situ recovery” <br>
Abstract : Uranium in situ recovery (ISR) is the most widely used uranium mining technique worldwide. It consists in dissolving the ore by a leaching solution, directly within the deposit. The absence of mechanical extraction gives ISR the advantage of being quick to deploy, but also of being less expensive and of lower surface environmental impact than open-pit and underground mining. However, as in the oil and gas industry, it offers an indirect view of the deposit and presents a high degree of uncertainty on the estimate of future production. By predicting flows and geochemical reactions within the reservoir, reactive transport (RT) is a powerful and suitable tool for understanding and managing an ISR operation. Therefore ORANO Mining and the Centre of Geoscience of MINES ParisTech have been developing for the past ten years a deterministic RT modeling approach dedicated to the simulation of ISR operations. The demonstration of the feasibility and robustness of reactive transport simulations for ISR was carried out in particular at KATCO, a mining site in Kazakhstan. However, large discrepancies between model and production data exist. The improvement of the results requires to solve the inverse problem for the reactive transport, which means performing a local refinement of the geological and geochemical models by optimization methods using past production data. <br>
<strong>Carlos Rufino Juarez de Leon</strong>, “Understanding and modelling of tundra gases escape mechanism 
from the ground to the atmosphere and their consequences during global warming” <br>
Abstract : Carbon concentration in atmosphere is increasing due to natural and anthropogenic emissions up until and unprecedent concentration for the last ~300 000 ybp. Time in which the Earth has had continuous glacial and interglacial periods.
Global Warming has strongly altered arctic and sub-arctic ecosystem through the alteration of Carbon and Nitrogen cycles. Permafrost plays an important role as it is considered a potential source of Carbon.
Permafrost is defined as the ground that remains below 0°C for at least two consecutive years. Its composition can be rocks or sediments and sometimes ice can be present. The amount of Carbon in permafrost in twice as greater as the Carbon in atmosphere (1600 Gt of Carbon).
Thawing permafrost could release this Organic Carbon and behave whether as CO2 source or enhance other processes for a possible CO2 sink. These processes could unchain different GHG such as Methane or Nitrous Oxide, which have a higher Warming Potential.
Permafrost degradation can have structural consequences, especially to the human infrastructure of the northern regions as well as the release of different dangerous chemical species (e. g. mercury) dissolved in water through redox reactions enhanced by the change of oxic or anoxic conditions.
The current project will focus on the gas analysis of the different species contributing to the Greenhouse effect through the concentration measure of different gaseous species in situ and laboratory procedures to analyse thaw behaviour and associated gases. <br>
<br>
<h3>
14h – 17h Presentations – room Outremer
</h3>
<strong>Boris Maletckii</strong>, “The Near Real Time Analysis of Ionospheric Disturbances in a near field by GNSS
data” <br>
Abstract : The ionosphere is a variable medium that is characterized by a significant number of different origins’ disturbances. They correspond to a wide range of phenomena, including natural hazards, space weather events, etc. One of the most challenging scientific questions is to identify such disturbances (known as traveling ionospheric disturbances or TID) and their origin, especially in real or near-real-time (NRT). In addition, its large presence and variability make it even more complex.
We developed a series of novel methods that enables to automatically detect TID in data series of total electron content (TEC) and to determine their spatio-temporal characteristics (instantaneous velocity field) in NRT, i.e., less than 15 minutes after an event occurrence and/or several minutes after the first detection of the disturbance.
The first method, called “D1-GNSS-RT”, is based on an interferometric approach called “D1” that uses three spatially separated GNSS-receivers as an interferometric system. The second method is NRT-compatible Travel Time Diagrams (TTD). Both of them use the TEC time derivative to detect TID’s signatures.
These methods are mostly suitable for detection of TID with a high rate of TEC change. Our analysis showed that TID driven by earthquakes (known as co-seismic TID, CTID), are characterized by the highest rate of TEC values as compared to TID of other origins. The list of other detectable, analyzable phenomena by our approach includes: volcanic eruptions, powerful explosions, solar flares and tsunamis.
Therefore, it should be possible to distinguish TID of different origins in NRT by using our methods. <br>
<strong>Marie Bouih</strong>, “Deep mass redistribution prior to the Maule earthquake revealed by GRACE satellite 
gravity”<br>
Abstract : The control on megathrust earthquake generation exerted by deeper subduction processes remains poorly understood and still insufficiently documented. Here, we use the 2003-2014 space-time variations of the Earth’s gravity gradients derived from the GRACE geoids in order to probe aseismic mass variations at depth and their possible interactions with intraplate seismicity along the Chilean margin. We work with three different datasets of GRACE geoid models over a large region surrounding the rupture zone of the Mw 8.8 2010 Maule earthquake. In order to separate signals associated with mass sources of differents sizes, shapes or orientations, we reconstruct each month the Earth’s gravity gradients at different spatial scales from these geoid models. Our analysis emphasizes a highly anomalous, large-amplitude gravity gradients signal that appears three months prior to the earthquake North of the epicentral zone, and progressively increases until the megathrustal rupture, in all three datasets. We show that this large signal cannot be caused by a shallow
hydrological source nor by GRACE striping artefacts and dealiasing models. Instead, we conclude that its most likely origin is in mass redistributions within the solid Earth on the continental side of the subduction zone. These anomalous gravity gradient variations could be explained by a deep extensional deformation of the slab around 150-km depth along the Nazca Plate subduction direction, driving large-scale fluid motion in the subduction
zone and into the overriding lithosphere. Our results highlight the importance of observations of the Earth’s time-varying gravity field from satellites to probe aseismic mass redistributions in-depth major plate boundaries . The detection of such mass redistributions at depth by GRACE and their interactions with interplate seismicity opens a new field of research to better characterize and understand the dynamics of the seismic cycle at megathrusts. <br>
<strong>Quang Nam Dam</strong>, “Noise propagation in LISA data and model validation with LISANode simulator”<br>
Abstract : After the first detection of gravitational wave (GW) by LIGO/Virgo detectors, we have been opened a new astronomy era to investigate our Universe, GW astronomy. To broaden the frequency band for the GW observation, Laser Interferometer Space Antenna (LISA) has been working to be the first space-based GW detector, aiming to detect the GW signals from various astrophysical sources and cosmological sources in the most sensitive band from 0.1 mHz to 1 Hz. To study the noises and how to reduce them in the LISA mission at the required levels for doing GW science, the noise budget of the performance model has been developed by LISA scientists, in particular the Performance working group. The performance model is one of the key elements in the phase A of the LISA mission. The noise budget will take into account all noises that could exist during the operation of the mission as well as the propagation of these noises through data processing methods. Some of these methods, the first to be applied on the raw data, have to reduce some dominant noises by several orders of magnitude. In particular, the Time Delay Interferometry (TDI) algorithm, which reduces the laser frequency noise and clock noises by combining several measurements, is a key step in data analysis. Then we need to study the propagation through TDI of all noises, which are reduced or not, as well as the GW signals in the data usable for the science exploitation. This result then is implemented in the noise performance model of the LISA mission to study instrument performances, sensitivity to various noises and scientific performances via the Figure of Merits, developed by the LISA Consortium to quickly evaluate science return of mission configuration. This talk is aiming to give an overview of how we propagate the noises through TDI algorithm to obtain the noise transfer function matrix. First, we will give a brief introduction about TDI, as well as the up-to-date beam model for the interferometer measurements that we used for the study. Then, the calculation of transfer functions for some noises will be presented. We are also taking into account for some realistic features like laser locking and correlated noises in some simple scenarios. Last but not least, we will talk about the model validation for consolidating the analytic result and the data from the LISANode simulator. <br>
15h – Break <br>
<strong>Nirmit Dhabaria</strong>, “An insight into the nature of a 70 Ma old crust and the Moho transition zone 
across the Saint Paul fracture zone near 18ᵒ W in the Equatorial Atlantic Ocean.” <br>
Abstract : The nature of the Moho transition zone has been a subject of considerable research to understand its evolution with the various hydrothermal, magmatic and tectonic processes occurring in the broadly mafic crust and ultramafic upper mantle. And although the thickness of an older oceanic crust formed across the fracture zones and along the spreading ridges largely remains unchanged, the nature of its lower crust and Moho remains a matter of considerable debate. 
We present a study to understand the nature of crust and the Moho transition zone using 2D elastic full-waveform inversion of an ocean bottom seismometer (OBS) data from a 70 Ma old crustal segment, north of the St. Paul fracture zone near 18ᵒ W parallel to the Mid-Atlantic Ridge in the equatorial Atlantic Ocean. 
The results highlight several low-velocity sub-horizontal layers in the lower crust and the presence of both sharp and gradient transition zones spread over an offset of 70 km. The presence/absence of P-S reflections seen at certain OBSs further consolidate these results and suggest an in-situ melt injection and crustal accretion. <br>
<strong>Roxane Tissandier</strong>, “The Mw 8.3 2015 Illapel afterslip imaged through a time-dependent inversion 
of continuous and survey GNSS data” <br>
Abstract : Postseismic slip of large earthquakes is expected to occur in the immediate vicinity of the main rupture. It is also expected to develop as a logarithmic function of time and to drive aftershocks evolution. According to rate-and-state friction law, it should occur in rate-strengthening and low-coupled areas whereas coseismic slip occurs in rate-weakening and high-coupled zones.
Here, we combine continuous and survey GNSS data to compute for the first time a full time-dependent inversion of the two-months afterslip following the Mw 8.3 2015 Illapel earthquake. We solve for the daily slip and show that, with a new fine analysis of the afterslip, we are able to know if it follows the rate-and-state law mentioned above. From this peculiar case, we infer that afterslip reveals a more complex process than just slip induced by stress increase in rate-strengthening areas.
As expected, afterslip develops at the edges of the coseismic rupture between the trench and 60 km depth. But it developed as discrete areas rather than surrounding the entire rupture, and also overlaps the deeper part of it. A modulation between afterslip and the three largest aftershocks on November, 7th and 11th is observed, with afterslip pulses while they rupture. We also find that afterslip discrete areas matches the postseismic seismicity (Frank et al., 2017), repeating earthquakes (Huang et al., 2017) and seismic swarms identified over 20 years prior to the Illapel earthquake (Poli et al., 2017) <br>
<strong>Pierre Boymond</strong>, “Volcano-tectonic interactions within two recently discovered submarine volcanic 
fields: Implication for geodynamics in the Comoros”<br>
Abstract : The birth of a new volcano offshore the eastern coast of Mayotte, one of the oldest volcanic island in the Comoros archipelago, rose questions about the origin of the volcanism in this area. The volcano-tectonic context of this region is poorly known mainly because high-resolution marine data was missing. Here we present new marine geophysical data (bathymetry, backscatter and seismic reflexion data) acquired between December 23 2020 and February 11 2021 during the SISMAORE cruise (Thinon et al., 2021) in the framework of the French ANR COYOTES project. The high-resolution multibeam bathymetric and backscatter data revealed the existence of two submarine volcanic provinces we named N’Dround´e and Mwezi (Thinon et al., 2022). In these provinces, we identified faults scarps, volcanic structures, lava flows and flat-top sedimentary domes on the seafloor. Those volcanic and tectonic features are very well preserved in the morphology and very reflective in the backscatter attesting that they are recent and probably active. Several seismic reflection profiles crosscut those structures. They reveal that the sedimentary layers are cut by faults and intruded by sills and dykes. We showed that the recent deformations of the seafloor such as flat-topped domes and grabens are promoted by those intrusions. The recent deformation of the sediments accommodating the magmatic intrusions are used as
indirect markers to establish a relative chronology of magmatic activity in the two volcanic provinces. We showed that the magmatism is older in the N’Dround´e volcanic province, near Grande Comore than in Mwezi’s, North-East of Anjouan. We also showed from the analysis of sills and dykes in the sedimentary cover that the magmatism intruded during two non-concurring episodes. Those volcano-tectonic features align in a mean NW-SE direction and may have likely emplaced in a NE-SW extensional stress field. At a smaller spatial scale, some diking-induced graben form swarms of different directions implying local perturbation of the regional stress field by volcanic intrusions. Overall, those observations are crucial to improve our knowledge of the geodynamics in the area and to constrain boundary conditions for future numerical modeling of deformation at lithospheric scale. <br>
<strong>Soumya Bohidar</strong>, “Seismic constraints on hydrothermal circulation and magmato-tectonic 
interactions beneath Lucky Strike volcano, Mid-Atlantic Ridge (MAR)”<br>
Abstract : Lucky Strike volcano, the central edifice of the Lucky Strike segment, MAR, overlies an axial magma chamber (AMC) and hosts one the largest known deep-sea hydrothermal fields. Here we present 12 years of seismicity, recorded beneath the volcano in between 2007-2019, as part of the EMSO-Azores observatory. We observe continuous seismicity (ML ~ -1 to 0), focused mainly 0.5-2km above the AMC and propose it to be caused by thermal contraction at the base of hydrothermal circulation. The main seismicity cluster have moved from its initial position at North-Northwest of hydrothermal field to its final position just beneath it during this period in two shifts. These shifts, of the order ~600-700 meters, might be driven by one or several of the following mechanisms: relocation of the maximum heat extraction zone to a shallower region of the AMC after significant heat extraction, relocation to a recent magmatic injection, and/or a tectonically driven change in hydrothermal fluid pathways. We detected three main Higher Seismic Activity periods: April-June 2009, August-September 2015, and April-May 2016. The 2009 HSA events clustered just above the AMC, while 2015 and 2016 HSA events appeared in a narrow, dike-shaped cluster between the AMC and just few meters below seafloor. In between HSA periods, seismicity tends to align along the trace of an inward dipping fault. The HSA periods can thus be interpreted as periods of maximum heat extraction by the hydrothermal circulation, possibly obscuring the background fault-related seismicity that is detected in periods of lesser seismic activity. <br>
<br>
<h2>
Friday 15th of April – Micro to macro
</h2>
9h30 – Breakfast <br>
10h – <strong>Samuel Abiven</strong> (ENS), “Carbon cycle in terrestrial ecosystems across scales - why scaling rarely 
works” – Amphitheatre <br>
<br>
<h3>
10h30 – 12h30 Poster session - Hallway <br>
</h3>
<strong>Mathias Regnier</strong>, “Bolometric Interferometry and QUBIC: asolution to Galactic foreground 
complexity for primordial B-modes search”. Keywords : Cosmology <br>
<strong>Arianna Rizzieri</strong>, “Component separation for the polarized microwave sky in view of next-
generation cosmic microwave background experiments”. Keywords : Cosmology, CMB, galactic foregrounds, thermal dust, synchrotron radiation, polarization, B-modes, LiteBIRD <br>
<strong>Magdy Morshed</strong>, “Partial-sky coverage of the Cosmic Microwave Background polarization in the 
context of Simons Observatory”. Keywords : Cosmology - Data analysis - Cosmic Microwave Background <br>
<strong>Alexandre Kompalitch</strong>, “Development of biomineralization approaches for the selective metal 
recovery from end-of-life products”. Keywords : Cosmology - Data analysis - Cosmic Microwave Background<br>
<strong>Chloé Goupy</strong>, “Detecting reactor neutrinos with the NUCLEUS Experiment”. Keywords : Reactor neutrinos, coherent scattering, cryogenic detectors, backgrounds and shielding <br>
<strong>Francesco Biagioli</strong>, “Field testing of fiber-optic distributed acoustic sensing (DAS) for volcanic 
monitoring in Stromboli”. Keywords : Seismology; Volcanology; volcanic monitoring; distributed acoustic sensing; optical fibers <br>
<strong>Antoine Demont</strong>, “Rheological influences on the growth of a detachement fault”. Keywords : Rheology, Numerical modeling, Geodynamics, Petrology<br>
<strong>Gabriel Devos</strong>, “Cadmium isotope compositions as a geochemical tracer”. Keywords : Geochemistry, cosmochemistry, volcanism<br>
<strong>Augustin Maller</strong>, “Metal fragmentation by large Earth-Forming impacts”. Keywords : Planet formation, Fluid dynamics, Fragmentation, Core formation, Planet differentiation<br>
<strong>Fei Zhou</strong>, “Variability of Sea-Surface Magnetic Anomalies at Ultraslow Spreading Centers: 
Consequence of Detachment Faulting and Contrasted Magmatism?”. Keywords : magnetic anomaly, Ultraslow spreading centers, detachment faulting, magmatism <br>
<strong>Colin Chanteloube</strong>, “Source-to-sink aeolian fluxes from arid landscape dynamics in the Lut Desert”. Keywords : Aeolian transport, Landscape dynamics, Source-to-sink, Dunes, Yardangs, Lut Desert<br>
<strong>Chagnon Glynn</strong>, “Brine Vs Marine Water as Sources of Halogen-rich Hydrothermal Fluids at La 
Soufrière de Guadeloupe”. Keywords : Hydrothermal systems, Volcanology, Numerical modelling, Geochemical modelling <br>
<strong>Maylis de La Serve</strong>, “Are there detectable common aperiodic displacements at ITRF co-location 
sites?”. Keywords : Geodesy, reference frame <br>
<strong>Sophie Coural</strong>, “Analysis of atmospheric nanoparticles by plane trees”. Keywords : Biogeochemistry, nanoparticles, pollution<br>
<strong>François Kamal Youssef</strong>, “Cosmic-Rays in local gas filaments”.Keywords : Astroparticles, Cosmic-Rays, Local interstellar medium, emissivity, Fermi, Planck, GASS <br>
<strong>Biswajit Biswas</strong>, “Deblending to study dark energy with weak lensing”. Keywords : cosmology, machine learning, dark energy, weak lensing  <br>
<br>
<h3>
14h – 17h Presentations – Amphitheatre<br>
</h3>
<strong>Konstantin Leyde</strong>, “Current and future constraints on cosmology and modified gravitational wave 
friction from binary black holes”<br>
Abstract : Gravitational wave (GW) standard sirens are well-established probes with which one can measure cosmological parameters, and are complementary to other probes like the cosmic microwave background or supernovae standard candles. Here we focus on dark GW sirens, specifically binary black holes (BBHs) for which there is only GW data. W rely on the assumption of a source mass model for the BBH distribution, and we consider four models that are representative of the BBH population observed so far. In addition to inferring cosmological and mass model parameters, we use dark sirens to test modified gravity theories. These theories often predict a different GW propagation, leading to a changed GW luminosity distance which in some cases can be parametrized by variables $\Xi_0$ and $n$. General relativity (GR) corresponds to $\Xi_0= 1$. We perform a joint estimate of the population parameters governing mass, redshift, cosmology, and GW propagation. We use data from the third LIGO-Virgo-KAGRA observation run (O3) and find — for the four mass models and three signal-to-noise cutoffs — that GR is consistently the preferred model to describe all observed BBH GW signals to date. Furthermore, all modified gravity parameters have posteriors that are compatible with the values predicted by GR at the $90\%$ confidence interval. We then focus on future observation runs O4 and O5. We show that there are strong correlations between cosmological, astrophysical and modified gravity parameters. If GR is the correct theory of gravity, and assuming narrow priors on the cosmological parameters, we recover the modified gravity parameter $\Xi_0 = 1.47^{+0.92}_{-0.57} $ with O4, and $\Xi_0 = 1.08 ^{+0.27}_{-0.16}$ with O4 and O5. If, however, Nature follows a modified gravity model with $\Xi_0=1.8$ and $n=1.91$, we exclude GR at the 1.7$\,\sigma$ level with O4 and at the $2.3\,\sigma$ level with O4 and O5 combined.  <br>
<strong>Gaspard Farge</strong>, “From the pore scale to the subduction scale -- how transient fluid processes shape 
microseismicity patterns”<br>
Abstract : Low-frequency tremor is detected in deep parts of subduction faults (30--60~km), in regions that host complex slip events and fluid circulation processes that generate rapid, strong fluid pressure transients. Spatio-temporal patterns of tremor can provide valuable insight into those phenomena. Tremor activity is characterized by its intermittence: it occurs in recurring, often quasi-periodic bursts. This behavior is often modeled as resulting from transient slip events, which spatio-temporal patterns are controlled by frictional properties of the fault interface. However, few studies account for the role that dynamic fluid processes play on shaping the intermittence of tremor. We build a model that links tremor to the activity of small permeability valves in a permeable fault interface, in order to investigate how the intensity of fluid flow and the concentration of permeability heterogeneities control the emergence of intermittent and periodic tremor activity. In this model, elementary fault valves act as tremor sources, and interact through pressure transients. This interaction is faster when the valves are closer, or when they are closer to critical opening/closing conditions. As a result of these interactions, valves synchronize, realistic intermittence patterns of activity emerge, and a system-wide valving behavior develops. By linking source-scale interactions to subduction-scale patterns of activity, our model helps conceptualize the role of the fluid circulation network and its dynamics in shaping tremor activity in subduction zones. It provides a general and powerful framework to understand how fluid processes can shape patterns of seismicity in other geologic system too, as continental faults or magmatic systems. <br>
<strong>Simon Bufféral</strong>, “Investigating the dynamics of the post-alpine dismantling in the Peloponnese 
(Greece) - a morphological approach”<br>
Abstract : Since the end of the progression of the Alpine thrusts in the Miocene, a widespread extensional trend has cut out the geodynamic landscape of the Peloponnese (Greece). While the rollback of the Hellenic slab is probably responsible for a significant part of it, as in the Aegean domain, this phenomenon doesn’t appear sufficient to explain the multiple directions of extensional faults nor the post-Alpine folds we observe today. 
In fact, the Peloponnese tectonic system seems to be organized around a core of exhumed deep units. Here, we present a set of tectonic clues for this dismantling and propose it as the main driver of a radial collapse of the Peloponnese, and of the associated rollover folding. We propose that this delamination occurs asymmetrically, i.e. essentially directed towards the gravimetric low of the Matapan Trough. This collapse thus slices the Hellenic backstop into a fan-shaped set of crustal blocks, bordered by normal faults of lithospheric scale that are potentially capable of causing major earthquakes and generating devastating tsunamis. <br>
15h – Break <br>
<strong>Linru Fang</strong>, “Half-life and initial Solar System abundance of 146Sm determined from the oldest 
andesitic meteorite”<br>
Abstract : The formation and differentiation of planetary bodies are dated using radioactive decay systems, including the short-lived 146Sm-142Nd (T1/2=103 or 68 Ma) and long-lived 147Sm-143Nd (T1/2=106 Ga) radiogenic pairs that provide relative and absolute ages, respectively. However, the initial abundance and half-life of the extinct radioactive isotope 146Sm are still debated, weakening the interpretation of 146Sm-142Nd systematics obtained for early planetary processes. Here, we apply the short-lived 26Al-26Mg, 146Sm-142Nd, and long-lived 147Sm-143Sm chronometers to the oldest known andesitic meteorite, Erg Chech 002 (EC 002), to constrain the Solar System initial abundance of 146Sm. The 26Al-26Mg mineral isochron of EC 002 provides a tightly-constrained initial 𝛿26Mg* of -0.009±0.005 ‰ and (26Al/27Al)0 of (8.89±0.09)×10-6. This initial abundance of 26Al is the highest measured so far in an achondrite and corresponds to a crystallization age of 1.80±0.01 Myr after Solar System formation. The 146Sm-142Nd mineral isochron returns an initial 146Sm/144Sm ratio of 0.00830±0.00032. By combining the Al-Mg crystallization age and initial 146Sm/144Sm ratio of EC 002 with previously determined values for CAIs, achondrites, and lunar samples, the best-fit half-life for 146Sm is 102 ± 9 Ma corresponding to the physically-measured value of 103 ± 5 Myr, rather than the latest and lower revised value of 68 ± 7 Ma. Using a half-life of 103 Ma for 146Sm, the 146Sm/144Sm abundance of EC 002 translates into an initial Solar System 146Sm/144Sm ratio of 0.00840±0.00032, which represents the most reliable and precise estimate to date and makes EC 002 an ideal anchor for the 146Sm-142Nd clock.  <br>
<strong>Julie Rode</strong>, “DarkSide-50: Characterisation of the LAr ionization response in the keV regime”<br>
Abstract : To gain higher sensitivity to light dark matter candidates direct detection experiments such as DarkSide need an excellent knowledge of the response of their detector in the low mass regime.  This is possible thanks to a robust detector response model and the calibration of the electron and nuclear recoil ionization response. The methodology will be presented along with the calibration results.  <br>
<strong>Ssu-Ting Lai</strong>, “Time-lapse rock deformation monitoring using waveform inversion”<br>
Abstract : Microscopic and macroscopic monitoring of crack evolution is a key to helping us understand the stress statement and seismic features of the failures. Microscopically, the measurement of rock properties under deformation in the laboratory provides us
with a comprehensive view of a rock’s dynamic and statistical characteristics. Together with macroscopic observation, laboratory-scale experiments of rock deformation have brought us the essential knowledge to understand the physics of earthquake nucleation. Understanding crack evolution is also critical in the industry for monitoring hydrocarbon and CO2 storage since their underground fluid injection in the reservoirs is known to trigger seismic fault ruptures. Therefore, imaging the timelapse storage scenarios, studying the sensitivity of the varying seismic response and investigating the rupture process is becoming indispensable and extremely important in industry and earthquake physics. This thesis proposes a state-of-the-art time-lapse wave-equation-based seismic imaging methodology to infer structural changes during rock deformation. We thus developed 0D time-lapse and 3D time-lapse (4D) active-source seismic imaging on rock samples in the laboratory, proposing an inversion method to efficiently image the elastic/anelastic structural changes during the deformation. <br>
<br>
<h3>
14h – 17h Presentations – room Outremer
</h3>
<strong>Maël Es-sayeh</strong>, “Updated radiative transfer model for titan: validation on vims-cassini observations 
of the huygens landing site and application to the analysis of the dragonfly landing area”<br>
Abstract : Titan, the only moon in the solar system with a thick atmosphere and a methane-based hydrological cycle similar to the water-based cycle on Earth, is a prime target for planetary and astrobiological researches. Organic materials from atmospheric chemistry precipitate on the surface and are subject to geological processes (e.g. eolian and fluvial erosion) that lead to the formation of dune fields, river networks, lakes and seas similar to their terrestrial counterparts. The analysis of the surface reflectance in the near-infrared (NIR) allows to constrain the surface composition, which is crucial to understand these atmosphere/surface interactions. However, Titan’s atmosphere prevents the surface from being probed in the NIR, except in 7 transmission windows (centered at 0.93, 1.08, 1.27, 1.59, 2.01, 2.7 and 5 μm). We use an updated version of the Radiative Transfer (RT) model of Hirtzig et al. (2013), with updated gases and aerosols opacities, in order to better simulate atmospheric absorption and scattering and retrieve surface albedos in the 7 NIR transmission windows with an enhanced accuracy. Our RT model is based on the SHDOMPP and CDISORT solvers to solve the RT equations in a plane- parallel and pseudo-spherical approximations respectively. We recently improve atmospheric inputs of the model with up-to-date gaseous CH4, CH3D, 13CH4, C2H2, HCN and CO abundances profiles and absorption coefficients, and improved the photochemical aerosol optical properties. In particular, the optical properties of Titan’s aerosols are now computed from a fractal aggregate model constrained by in situ measurements of the Descent Imager/Spectral Radiometer (DISR) onboard the Huygens probe. Our RT model is benchmarked with the help of the most recent RT model for Titan in the literature and validated using the in situ observations of DISR acquired during descent and once landed. Coupled with an efficient inversion scheme, our model can be apply to the Cassini’s Visual and Infrared Mapping Spectrometer (VIMS) complete dataset for the retrieval of Titan’s atmospheric opacity and surface albedos at regional and global scales. This will help to analyze the near-future observations of Titan with the James Webb Space Telescope (JSWT) and prepare the future exploration of Titan by the Dragonfly mission. <br>
<strong>Ting Tan</strong>, “Detection of Baryon Acoustic Oscillations using Lyman-α Forests in DESI”<br>
Abstract : The Dark Energy Survey Instrument (DESI) is a stage-IV spectrographic sky survey that will measure the expansion of the Universe and constrain dark energy models. Conducted with the Mayall 4-meter telescope at Kitt Peak National Observatory in the U.S.A, DESI will measure the spectra of more than 30 million galaxies and quasars covering 14,000 square degrees across the sky during its 5-year observation time (Started on 17/05/2021). The study of Baryon Acoustic Oscillations (BAO) with Lyman-α forests is one of the main projects in DESI. The Lyman-α forest is a series of absorption lines in the spectra of distant quasars. Those absorptions are caused by the Lyman-alpha electron transitions when photons traverse through the neutral hydrogen regions in the Universe. Lyman-α forests can be used as biased matter tracers that trace the underlying dark matter distribution, to detect the BAO signal, which reveals the primordial fluctuations of the matter fields in the early stage of the universe when it was still a plasma. It demonstrates how a sound wave traveled through the universe between the Big Bang and the epoch of recombination, and is used as a large-scale structure probe to study the cosmological models and in particular, dark energy models, by measuring the expansion of the universe.  <br>
<strong>Lea Ostorero</strong>, “Correlating diffusive timescales in crystals with monitoring signals leading to 
explosive eruptions”<br>
Abstract : The increase of number and intensity of earthquakes preceding an eruption is the main basis of seismic volcano monitoring. However, the exact relationship between the seismic activity and the volcano-magmatic processes remains unclear. Spatiotemporal magma storage and dynamics can be investigated by coupling timescale modelling and the study of the diversity of crystal compositions. Here we present a direct comparison between a seismo-volcanic crisis recorded prior to the 2010-2013 eruption of Kizimen volcano (Kamchatka, Russia) and the timescales of processes in the magma plumbing system. These timescales are inferred from the analysis of orthopyroxene crystals from dacites and silica-rich andesites samples collected after the eruption. By modelling the Fe-Mg intracrystalline interdiffusion in 88 zoned orthopyroxene crystals, we show that the eruptible magmas were assembled rapidly during a magma mixing episode ~1.5 years before the eruption. We conclude that the observed seismic re-activation also beginning ~1.5 years before the eruption, marks the onset of magma mixing leading to destabilization of the shallow reservoir followed by the eruption. At Bezymianny volcano, also in Kamchatka, the pre-eruptive dynamics of the 1956 catastrophic eruption following the injection of a cryptodome into the flank of the volcano were studied. Timescales of the reactivation of the reservoir were determined from zoned orthopyroxenes and ascent rates and residence timescales into the cryptodome were determined from zoned titanomagnetites. <br>
15h – Break <br>
<strong>Sabrina Menina</strong>, “Earth-Moon-Mars coda attenuation comparison”<br>
Abstract : The comparison Earth Mars Moon from a seismological point of view is possible today with the NASA-Insight (Interior exploration using Seismic Investigations, Geodesy and Heat Transport) mission on Mars. Since its deployment at the surface of the red planet, the seismometer SEIS (Seismic Experiment for Interior Structure) recorded hundreds of Very High Frequency (1.5 – 15Hz; VF) small magnitude seismic events. They are characterized by two temporally separated arrivals with a gradual beginning, a broad maximum and a very long decay. These basic observations suggest that the VF events are generated by the long-range propagation of seismic P and S waves in a heterogeneous crust. In this work, we propose to use seismic coda analysis to explore the properties of Martian crust and to provide an Earth-Mars-Moon attenuation proprieties comparison. We found that the diffusivity on Mars ranges  from 50 to 800 km2/s, which suggests that the scattering attenuation is  much more Earth-like than Moon-like. As for the attenuation, with an intrinsic quality factor ranging from 3500 to 10000, Mars is found to be much more Moon-like than Earth-like. The albedo  of the Martian lithosphere is extremely high, typically of the order of 0.9, in sharp contrast with the Earth where the albedo rarely exceeds 0.5. This suggests that the upper crust in the equatorial region near InSight could be mostly dry.  <br>
<strong>Souradeep Mahato</strong>, “Strain localization in mid-ocean ridge detachment faults: multiscale study of a 
nearly amagmatic endmember case (64°40’E Southwest Indian Ridge)”<br>
Abstract : The easternmost part of the SWIR is an ultraslow-spreading (14mm/yr), melt-poor end member region of Mid-Ocean ridge system, with corridors of nearly-amagmatic seafloor spreading where plate divergence occurs almost fully via large-offset (~10-20 km), alternate-polarity, normal faults also called detachment faults (Sauter et al., 2013), that exhume serpentinized peridotites to the seafloor. Here we present a map to sample scale study of deformation in the presently active axial detachment fault and contrast our results to observations at more magmatically active Mid-Atlantic Ridge (MAR) detachments.  The detachment fault we study emerges over more than 50 km along-axis, compared to 5-15 km for the scoped-shaped MAR exhumed detachment surfaces (eg Escartin et al., 2017). The emergence domain is complex, with km-scale irregularities and locally with several active splays distant by ~ 100 meters. Landslide scars offer up to 70 m-high vertical sections in the deformed footwall, showing a highly heterogeneous deformation with decimeter to pluri-meter-thick horizons of serpentinite micro-breccia and gouges, intercalated with sigmoidal-shaped domains of coarser serpentinite breccia and blocks of massive serpentinite. Deformation mechanisms are dominantly brittle, however we document millimeter to decimeter-scale horizons of semi-brittle micro-breccia, in which hydrous fluids circulating in the fault zone have favored local recrystallization of serpentine, leading to further strain localization. This differs with observations made at MAR detachments, where cataclastic deformation appears more localized and where semi-brittle higher strain horizons contain talc-amphibole-chlorite-serpentine assemblages that result from the hydrous alteration of mafic-ultramafic mixtures (eg peridotites injected by gabbro or basalt; Boschi et al., 2006; Picazo et al., 2012).<br>
<br>
<h3>
17h - Best poster award- 6th floor
</h3>
<br>
<h3>
17h15 Concert – Terrasse de l’IPGP
</h3>
</p>
